experiment:
  name: time_to_peak_prediction
  base_dir: experiments/
  description: Time to peak prediction with improved model

data:
  train_dir: data/token_data_2025-01-08.csv
  val_dir: data/token_data_2025-01-07.csv
  num_workers: 4
  dataset_params:
    normalize: true
    augment: true
    cache_data: true

model:
  input_size: 11  # Number of base features
  hidden_size: 256
  num_layers: 3
  dropout_rate: 0.5
  num_heads: 8
  use_cross_attention: true
  survival_prob: 0.8

training:
  epochs: 100
  batch_size: 32
  use_amp: true
  max_grad_norm: 1.0
  early_stopping_patience: 10
  checkpoint_frequency: 1
  
  optimizer:
    type: AdamW
    lr: 0.001
    weight_decay: 0.01
    betas: [0.9, 0.999]
  
  scheduler:
    type: one_cycle
    max_lr: 0.001
    pct_start: 0.3
    div_factor: 25.0
    final_div_factor: 10000.0

  loss_type: gaussian_nll

logging:
  use_wandb: false  # Set to true if you want to use Weights & Biases
  wandb_project: time_to_peak
  log_frequency: 100

# Paths
checkpoint_dir: checkpoints/
results_dir: results/
log_dir: logs/