_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.11
            "5": 0.19.2
            "8":
                - 3
                - 5
            "12": 0.19.2
            "13": windows-amd64
batch_size:
    value: 32
epochs:
    value: 200
learning_rate:
    value: 0.001
model_type:
    value: RealTimePeakPredictor
optimizer:
    value: AdamW
scheduler:
    value: OneCycleLR
weight_decay:
    value: 0.01
